---
title: "Gj1_computing"
author: "Jin Ge"
date: "2/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = F,
                      message = F)

require(survival)
library(broom)
library(tidyverse)
source("./sim.R")
```


```{r}
## generate the data of weibull
sim_survival=function(N){
  
data = generate_data(N = 500, beta = 4, distribution = "weibull", lambda = 0.1, gamma = 4, alpha = 4)

  # Fit three survival distributions
  fit.exponential = survreg(Surv(data$time) ~ data$x, dist = "exponential") 
  fit.weibull = survreg(Surv(data$time) ~ data$x, dist = "weibull")
  fit.cox = coxph(Surv(data$time) ~ data$x) 
  
  # Save beta coefficients 
  exp_beta = -fit.exponential$coefficients[-1]
  weibull_beta = -fit.weibull$coefficients[-1] / fit.weibull$scale
  cox_beta = fit.cox$coefficients[1]
  
  tibble(
    exp_beta=exp_beta,
    weibull_beta=weibull_beta,
    cox_beta=cox_beta
  )
 
}


sim_results = 
  tibble(sample_size = seq(100,500, by =20)) %>% 
  mutate(
    output_list=map(.x=sample_size, ~rerun(100,sim_survival(N=.x))),
    output_df=map(output_list,bind_rows)) %>% 
  select(-output_list) %>% 
  unnest()


mse_sim=function(x){
  c=0
  for(i in 1:100){
c=sum((x[i]-4)^2)/100
return(c)
  }
}

bias_sim=function(x){
  d=0
  for(i in 1:100){
d=sum((x[i]-4))/100
return(d)
  }
}


exp_data=sim_results %>% 
  select(sample_size,exp_beta)%>% 
  group_by(sample_size) %>% 
  summarize(beta_mean = mean(exp_beta),
            beta_var = var(exp_beta),
             beta_MSE = mse_sim(exp_beta),
            beta_bias=bias_sim(exp_beta))

weibull_data=sim_results %>% 
  select(sample_size,weibull_beta)%>% 
  group_by(sample_size) %>% 
  summarize(beta_mean = mean(weibull_beta),
            beta_var = var(weibull_beta),
             beta_MSE = mse_sim(weibull_beta),
            beta_bias=bias_sim(weibull_beta))

cox_data=sim_results %>% 
  select(sample_size,cox_beta) %>% 
  group_by(sample_size) %>% 
  summarize(beta_mean = mean(cox_beta),
            beta_var = var(cox_beta) ,
            beta_MSE = mse_sim(cox_beta),
            beta_bias=bias_sim(cox_beta))

exp_data=exp_data %>% 
  mutate(
    type="exp"
  )
weibull_data=weibull_data %>% 
  mutate(
    type="weibull"
  )

cox_data=cox_data %>% 
  mutate(
    type="cox"
  )

total=bind_rows(exp_data,weibull_data,cox_data)

## mse line
mse_weibull <- ggplot(data=total,aes(x=sample_size,y=beta_MSE,color=type))+
  geom_line(size = 1)+
  labs(title="MSE change with sample size",
       y = "MSE of beta",
       x = "Sample size")+
  theme_light()
mse_weibull

## smooth line of mse
ggplot(data=total,aes(x=sample_size,y=beta_MSE,color=type))+
  geom_smooth(se = F, method = "loess")+labs(title="MSE change with sample size")

## boxplot of mse when sample size is 500

box_plot_data=sim_results %>% filter(sample_size==500) %>% 
   pivot_longer(
    exp_beta:cox_beta,
    names_to=("type"),
    values_to = ("beta"))


ggplot(data=box_plot_data,aes(x=type,y=beta,color=type))+
  geom_boxplot()+
  labs(title="beta distribution among three models when sample size=500") +
  theme_light()
```


```{r proportional hazard}
# Write a function for simulations
simulate = function(sim, N, beta, censor = FALSE) {
  # Set up coefficient vectors
  exp_beta = rep(NA, sim)
  weibull_beta = rep(NA, sim)
  cox_beta = rep(NA, sim)
  
  # Censored Data
  if (censor == TRUE) {
    
    for (i in 1:sim) {
      # Generate data
      data = generate_data(N, beta, distribution = "weibull", 
                           lambda = 0.1, gamma = 4, alpha = 4)
      # Fit three survival distributions
      fit.exponential = survreg(Surv(data$observed_time, data$status) ~ data$x, dist = "exponential") 
      fit.weibull = survreg(Surv(data$observed_time, data$status) ~ data$x, dist = "weibull")
      fit.cox = coxph(Surv(data$observed_time, data$status) ~ data$x)
  
       # Save beta coefficients 
      exp_beta[i] = -fit.exponential$coefficients[-1]
      weibull_beta[i] = -fit.weibull$coefficients[-1] / fit.weibull$scale
      cox_beta[i] = fit.cox$coefficients[1]
    }
    
  # Uncensored Data
  } else {
    
    for (i in 1:sim) {
      # Generate data
      data = generate_data(N, beta, distribution = "weibull", 
                           lambda = 0.1, gamma = 4, alpha = 4)
      # Fit three survival distributions
      fit.exponential = survreg(Surv(data$time) ~ data$x, dist = "exponential") 
      fit.weibull = survreg(Surv(data$time) ~ data$x, dist = "weibull")
      fit.cox = coxph(Surv(data$time) ~ data$x)
  
       # Save beta coefficients 
      exp_beta[i] = -fit.exponential$coefficients[-1]
      weibull_beta[i] = -fit.weibull$coefficients[-1] / fit.weibull$scale
      cox_beta[i] = fit.cox$coefficients[1]
    }
    
  }
  
  # Store beta coefficients
  coef = tibble(exp = exp_beta,
                weibull = weibull_beta,
                cox = cox_beta)
  
  # Calculate bias and MSE for each model
  exp_bias = (sum(exp_beta - beta)) / sim 
  weibull_bias = (sum(weibull_beta - beta)) / sim
  cox_bias = (sum(cox_beta - beta)) / sim
  exp_MSE = (sum((beta - exp_beta)^2)) / sim
  weibull_MSE = (sum((beta - weibull_beta)^2)) / sim
  cox_MSE = (sum((beta - cox_beta)^2)) / sim
  
  # Store performance measures in a dataset
  perf_data = tibble(model = c("exp", "weibull", "cox"),
                     bias = c(exp_bias, weibull_bias, cox_bias),
                     mse = c(exp_MSE, weibull_MSE, cox_MSE))
  
  results = list(coef, perf_data)
  names(results) = c("coefficients", "performance")
  return(results)
}

# Simulation for different sample sizes
set.seed(12345)
sim_results = 
  tibble(sample_size = c(100, 150, 200, 250, 300, 350, 400, 450, 500)) %>% 
  mutate(
    output_uncensored = map(.x = sample_size, ~simulate(sim = 1000, N = .x, beta = 4)$performance),
    output_censored = map(.x = sample_size, ~simulate(sim = 1000, N = .x, beta = 4, censor = TRUE)$performance),
    output_uncensored = map(.x = output_uncensored, ~mutate(.x, censor = FALSE)),
    output_censored = map(.x = output_censored, ~mutate(.x, censor = TRUE))) 

# Join censored and uncensored data
temp1 = sim_results %>% unnest(output_uncensored) %>% select(-output_censored)
temp2 = sim_results %>% unnest(output_censored) %>% select(-output_uncensored)
samp_size_sim = rbind(temp1, temp2)

# Plot MSE simulation results
samp_size_sim %>% 
  mutate(censor = factor(censor, labels = c("Uncensored", "Censored"))) %>% 
  ggplot(aes(x = sample_size, y = mse, color = model)) + 
  geom_point() +
  geom_line(size = 1, se = FALSE) +
  facet_grid(.~censor, scales = "free_y") +
  labs(title = "Sample size vs MSE by Survival Model",
       x = "Sample Size",
       y = "MSE") +
  theme_bw() + 
  theme(strip.text.x = element_text(size = 12)) + 
  theme(text = element_text(size = 10),
        legend.text=element_text(size = 10))

# Plot bias simulation results
samp_size_sim %>% 
  mutate(censor = factor(censor, labels = c("Uncensored", "Censored"))) %>% 
  ggplot(aes(x = sample_size, y = bias, color = model)) + 
  geom_point() +
  geom_line(size = 1, se = FALSE) +
  facet_grid(.~censor, scales = "free_y") +
  labs(title = "Sample size vs Bias by Survival Model",
       x = "Sample Size",
       y = "Bias") +
  theme_bw() + 
  theme(strip.text.x = element_text(size = 12)) + 
  theme(text = element_text(size = 10),
        legend.text=element_text(size = 10))



```

