---
title: "Scenario 3: Non-parametric Cox Model"
author: "Adina Zhang"
date: "February 7, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(survival)
source("./sim.R")
```

```{r, message = FALSE, warning = FALSE}
# Write a function for simulations
simulate = function(sim, N, beta, censor = FALSE) {
  # Set up coefficient vectors
  exp_beta = rep(NA, sim)
  weibull_beta = rep(NA, sim)
  cox_beta = rep(NA, sim)
  
  # Censored Data
  if (censor == TRUE) {
    
    for (i in 1:sim) {
      # Generate data
      data = generate_data(N, beta, distribution = "weibull", 
                           lambda = 0.1, gamma = 4, alpha = 4)
      # Fit three survival distributions
      fit.exponential = survreg(Surv(data$observed_time, data$status) ~ data$x, dist = "exponential") 
      fit.weibull = survreg(Surv(data$observed_time, data$status) ~ data$x, dist = "weibull")
      fit.cox = coxph(Surv(data$observed_time, data$status) ~ data$x)
  
       # Save beta coefficients 
      exp_beta[i] = -fit.exponential$coefficients[-1]
      weibull_beta[i] = -fit.weibull$coefficients[-1] / fit.weibull$scale
      cox_beta[i] = fit.cox$coefficients[1]
    }
    
  # Uncensored Data
  } else {
    
    for (i in 1:sim) {
      # Generate data
      data = generate_data(N, beta, distribution = "cox", 
                           lambda = 0.1, gamma = 4, alpha = 4)
      # Fit three survival distributions
      fit.exponential = survreg(Surv(data$time) ~ data$x, dist = "exponential") 
      fit.weibull = survreg(Surv(data$time) ~ data$x, dist = "weibull")
      fit.cox = coxph(Surv(data$time) ~ data$x)
  
       # Save beta coefficients 
      exp_beta[i] = -fit.exponential$coefficients[-1]
      weibull_beta[i] = -fit.weibull$coefficients[-1] / fit.weibull$scale
      cox_beta[i] = fit.cox$coefficients[1]
    }
    
  }
  
  # Store beta coefficients
  coef = tibble(exp = exp_beta,
                weibull = weibull_beta,
                cox = cox_beta)
  
  # Calculate bias and MSE for each model
  exp_bias = (sum(exp_beta - beta)) / sim 
  weibull_bias = (sum(weibull_beta - beta)) / sim
  cox_bias = (sum(cox_beta - beta)) / sim
  exp_MSE = (sum((beta - exp_beta)^2)) / sim
  weibull_MSE = (sum((beta - weibull_beta)^2)) / sim
  cox_MSE = (sum((beta - cox_beta)^2)) / sim
  
  # Store performance measures in a dataset
  perf_data = tibble(model = c("exp", "weibull", "cox"),
                     bias = c(exp_bias, weibull_bias, cox_bias),
                     mse = c(exp_MSE, weibull_MSE, cox_MSE))
  
  results = list(coef, perf_data)
  names(results) = c("coefficients", "performance")
  return(results)
}


```


```{r, warning = FALSE}
# Simulation for different sample sizes
set.seed(12345)
sim_results = 
  tibble(sample_size = c(100, 150, 200, 250, 300, 350, 400, 450, 500)) %>% 
  mutate(
    output_uncensored = map(.x = sample_size, ~simulate(sim = 10, N = .x, beta = 4)$performance),
    output_censored = map(.x = sample_size, ~simulate(sim = 10, N = .x, beta = 4, censor = TRUE)$performance),
    beta_uncensored = map(.x = sample_size, ~simulate(sim = 10, N = .x, beta = 4)$coefficients),
    beta_censored = map(.x = sample_size, ~simulate(sim = 10, N = .x, beta = 4, censor = TRUE)$coefficients),
    output_uncensored = map(.x = output_uncensored, ~mutate(.x, censor = FALSE)),
    output_censored = map(.x = output_censored, ~mutate(.x, censor = TRUE))) 

# Join censored and uncensored data
temp1 = sim_results %>% unnest(output_uncensored) %>% select(-beta_uncensored:output_censored)
temp2 = sim_results %>% unnest(output_censored) %>% select(-beta_uncensored:output_uncensored)
samp_size_sim = rbind(temp1, temp2)

# Plot MSE simulation results
samp_size_sim %>% 
  mutate(censor = factor(censor, labels = c("Uncensored", "Censored"))) %>% 
  ggplot(aes(x = sample_size, y = mse, color = model)) + 
  geom_point() +
  geom_line(size = 1, se = FALSE) +
  facet_grid(.~censor, scales = "free_y") +
  labs(title = "Sample size vs MSE by Survival Model",
       x = "Sample Size",
       y = "MSE") +
  theme_bw() + 
  theme(strip.text.x = element_text(size = 12)) + 
  theme(text = element_text(size = 10),
        legend.text=element_text(size = 10))

# Plot bias simulation results
samp_size_sim %>% 
  mutate(censor = factor(censor, labels = c("Uncensored", "Censored"))) %>% 
  ggplot(aes(x = sample_size, y = bias, color = model)) + 
  geom_point() +
  geom_line(size = 1, se = FALSE) +
  facet_grid(.~censor, scales = "free_y") +
  labs(title = "Sample size vs Bias by Survival Model",
       x = "Sample Size",
       y = "Bias") +
  theme_bw() + 
  theme(strip.text.x = element_text(size = 12)) + 
  theme(text = element_text(size = 10),
        legend.text=element_text(size = 10))

```

```{r, warning = FALSE}
# Simulation for different effect sizes
set.seed(12345)
sim_results_beta = 
  tibble(beta = c(0.1, 0.5, 1, 3, 5, 6)) %>% 
  mutate(
    output_uncensored = map(.x = beta, ~simulate(sim = 500, N = 100, beta = .x)$performance),
    output_censored = map(.x = beta, ~simulate(sim = 500, N = 100, beta = .x, censor = TRUE)$performance),
    output_uncensored = map(.x = output_uncensored, ~mutate(.x, censor = FALSE)),
    output_censored = map(.x = output_censored, ~mutate(.x, censor = TRUE))) 

# Join censored and uncensored data
temp1 = sim_results_beta %>% unnest(output_uncensored) %>% select(-output_censored)
temp2 = sim_results_beta %>% unnest(output_censored) %>% select(-output_uncensored)
beta_sim = rbind(temp1, temp2)

# Plot MSE simulation results
beta_sim %>% 
  filter(beta != 6) %>% 
  mutate(censor = factor(censor, labels = c("Uncensored", "Censored"))) %>% 
  ggplot(aes(x = beta, y = mse, color = model)) + 
  geom_point() +
  geom_line(size = 1) +
  facet_grid(.~censor) +
  labs(title = "Beta vs MSE by Survival Model",
       x = "Beta",
       y = "MSE") +
  theme_bw() + 
  theme(strip.text.x = element_text(size = 12)) + 
  theme(text = element_text(size = 10),
        legend.text=element_text(size = 10))

# Plot bias simulation results
beta_sim %>% 
  filter(beta != 6) %>% 
  mutate(censor = factor(censor, labels = c("Uncensored", "Censored"))) %>% 
  ggplot(aes(x = beta, y = bias, color = model)) + 
  geom_point() +
  geom_line(size = 1) +
  facet_grid(.~censor) +
  labs(title = "Beta vs Bias by Survival Model",
       x = "Beta",
       y = "Bias") +
  theme_bw() + 
  theme(strip.text.x = element_text(size = 12)) + 
  theme(text = element_text(size = 10),
        legend.text=element_text(size = 10))

```

