---
title: "scenario1-sibeiliu"
author: "Sibei Liu"
date: "2020/2/8"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F,message = F)
require(survival)
library(broom)
library(tidyverse)
source("./sim.R")
```



```{r}
 #data generate

n_circle=1000
sim_survival=function(N){
  
data = generate_data(N, beta = 4, distribution = "exponential", lambda = 0.1, gamma = 4, alpha = 4)

  # Fit three survival distributions
  fit.exponential = survreg(Surv(data$time,data$status) ~ data$x, dist = "exponential") 
  fit.weibull = survreg(Surv(data$time,data$status) ~ data$x, dist = "weibull")
  fit.cox = coxph(Surv(data$time,data$status) ~ data$x) 
  
  # Save beta coefficients 
  exp_beta = -fit.exponential$coefficients[-1]
  weibull_beta = -fit.weibull$coefficients[-1] / fit.weibull$scale
  cox_beta = fit.cox$coefficients[1]
  
  tibble(
    exp_beta=exp_beta,
    weibull_beta=weibull_beta,
    cox_beta=cox_beta
  )
 
}

sim_results = 
  tibble(sample_size = seq(100,500,by=20)) %>% 
  mutate(
    output_list=map(.x=sample_size, ~rerun(n_circle,sim_survival(N=.x))),
    output_df=map(output_list,bind_rows)) %>% 
  select(-output_list) %>% 
  unnest()
    
mse_sim=function(x){
  c=0
  for(i in 1:n_circle){
 c=mean((x[i]-4)^2)
return(c)
  }
}

bias_sim=function(x){
  d=0
  for(i in 1:n_circle){
d=mean((x[i]-4))
return(d)
  }
}


exp_data=sim_results %>% 
  select(sample_size,exp_beta)%>% 
  group_by(sample_size) %>% 
  summarize(beta_mean = mean(exp_beta),
            beta_var = var(exp_beta),
             beta_MSE = mse_sim(exp_beta),
            beta_bias=bias_sim(exp_beta))

weibull_data=sim_results %>% 
  select(sample_size,weibull_beta)%>% 
  group_by(sample_size) %>% 
  summarize(beta_mean = mean(weibull_beta),
            beta_var = var(weibull_beta),
             beta_MSE = mse_sim(weibull_beta),
            beta_bias=bias_sim(weibull_beta))

cox_data=sim_results %>% 
  select(sample_size,cox_beta) %>% 
  group_by(sample_size) %>% 
  summarize(beta_mean = mean(cox_beta),
            beta_var = var(cox_beta) ,
            beta_MSE = mse_sim(cox_beta),
            beta_bias=bias_sim(cox_beta))
exp_data=exp_data %>% 
  mutate(
    type="exp"
  )
weibull_data=weibull_data %>% 
  mutate(
    type="weibull"
  )

cox_data=cox_data %>% 
  mutate(
    type="cox"
  )

total=bind_rows(exp_data,weibull_data,cox_data)

## mse line
ggplot(data=total,aes(x=sample_size,y=beta_MSE,color=type))+geom_smooth(se=FALSE)+labs(title="MSE change with sample size")

## boxplot of mse when sample size is 500

box_plot_data=sim_results %>% filter(sample_size==500) %>% 
   pivot_longer(
    exp_beta:cox_beta,
    names_to=("type"),
    values_to = ("beta"))


ggplot(data=box_plot_data,aes(x=type,y=beta,color=type))+geom_boxplot()+labs(title="beta distribution among three models when sample size=500")


## 
ggplot(data=total,aes(x=sample_size,y=beta_bias,color=type))+geom_smooth(se=FALSE)+labs(title="Bias change with sample size")

```


